create table USERS (
UName VARCHAR(160) NOT NULL,
UEmail VARCHAR(24) NOT NULL,
PRIMARY KEY (UName)
);

create table REVIEW (
REVID INT(12) NOT NULL AUTO_INCREMENT,
REVNAME VARCHAR(24) NOT NULL,
CurrRev BLOB NOT NULL,
FName VARCHAR(40),
DT VARCHAR(40) NOT NULL,
PRIMARY KEY (REVID)
);

CREATE TABLE WORKS_ON_PROJECTS (
REVIDREF INT(12),
UNameW VARCHAR(160),
FOREIGN KEY(UNameW) REFERENCES USERS(UName),
FOREIGN KEY(REVIDREF) REFERENCES REVIEW(REVID)
);

CREATE TABLE COMMENTS_ON_REVIEWS (
REVIDREF INT(12),
COMMID INT(12),
DT VARCHAR(40) NOT NULL,
COMM VARCHAR(1024),
UNameC VARCHAR(160),
PRIMARY KEY(COMMID),
FOREIGN KEY(REVIDREF) REFERENCES REVIEW(REVID),
FOREIGN KEY(UNameC) REFERENCES USERS(UName)
);

CREATE TABLE COMMITS (
CommID INT(12) NOT NULL AUTO_INCREMENT,
CommMessage VARCHAR(255),
CommAppro BOOLEAN NOT NULL DEFAULT '0',
DT VARCHAR(40) NOT NULL,
WhatRevID INT(12) NOT NULL,
UNameCom VARCHAR(160),
FOREIGN KEY(UNameCom) REFERENCES USERS(UName),
PRIMARY KEY(CommID),
FOREIGN KEY(WhatRevID) REFERENCES REVIEW(REVID)
);

CREATE TABLE INVITE_TO_REV (
RIID INT(12) NOT NULL AUTO_INCREMENT,
RIREVID INT(12),
RIUNAME VARCHAR(160),
RFUNAME VARCHAR(160),
DT VARCHAR(40),
ACCEPTED BOOLEAN NOT NULL DEFAULT '0',
FOREIGN KEY(RIUNAME) REFERENCES USERS(UName),
FOREIGN KEY(RFUNAME) REFERENCES USERS(UName),
FOREIGN KEY(RIREVID) REFERENCES REVIEW(REVID),
PRIMARY KEY(RIID)
);

CREATE TABLE COMMITS_ON_REVIEWS (
CommID INT(12),
REVID INT(12),
CommDT VARCHAR(40) NOT NULL,
CommDiff LONGBLOB,
FOREIGN KEY(CommID) REFERENCES COMMITS(CommID),
FOREIGN KEY(REVID) REFERENCES REVIEW(REVID)
);

CREATE TABLE INVITES (
IID INT(12) NOT NULL AUTO_INCREMENT,
IREVID INT(12),
IUNAME VARCHAR(160),
FUNAME VARCHAR(160),
DT VARCHAR(40),
ACCEPTED BOOLEAN NOT NULL DEFAULT '0',
FOREIGN KEY(IUNAME) REFERENCES USERS(UName),
FOREIGN KEY(FUNAME) REFERENCES USERS(UName),
FOREIGN KEY(IREVID) REFERENCES REVIEW(REVID),
PRIMARY KEY(IID)
);
